server:
  port: 8080

wechat:
  pay:
    # 微信公众号或者小程序等的appId
    appId: XXXX
    # 微信支付商户号
    merchantId: XXXX
    # 商户API私钥
    privateKeyPath: /apiclient_key.pem
    # 商户证书序列号
    merchantSerialNumber: XXXXX
    # 商户APIv3密钥
    apiV3key: XXXXX
    # 支付回调通知地址
    payNotifyUrl: https://XXXXXXXXXXX/api/v1/wechat/pay/callback