server:
  port: 8080

wechat:
  pay:
    # 微信公众号或者小程序等的appId
    appId: XXX
    # 微信支付商户号
    merchantId: XXX
    # 商户证书路径
    certPemPath: /apiclient_cert.pem
    # 商户API私钥路径
    privateKeyPath: /apiclient_key.pem
    # 商户APIv3密钥
    apiV3key: XXXX
    # 支付回调通知地址
    payNotifyUrl: https://XXXX/api/callback/wechat/pay/callback

redis:
  # redis服务地址
  host: XXX
  # 端口号
  port: 6379


config:
  bot:
    # 企业微信告警通知地址
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx